---
- name: install uStreamer
  import_tasks: ustreamer.yml

- name: install nginx
  import_tasks: nginx.yml

- name: install HID USB gadget
  import_tasks: install_usb_gadget.yml

- name: install TinyPilot pre-requisite packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - python-pip
      - python3-venv
      - sudo

- name: create tinypilot group
  group:
    name: "{{ tinypilot_group }}"
    state: present

- name: create tinypilot user
  user:
    name: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"
    system: yes
    create_home: no

- name: copy update script
  copy:
    src: update
    dest: "{{ tinypilot_privileged_dir }}/update"
    owner: root
    group: root
    mode: '0700'

- name: store passwordless sudo paths
  set_fact:
    sudo_paths:
      - /sbin/shutdown
      - "{{ tinypilot_privileged_dir }}/update"

- name: enable tinypilot to execute a whitelist of commands as sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ tinypilot_user }} ALL=(ALL) NOPASSWD: {{ sudo_paths | join(', ') }}"

- name: create TinyPilot folder
  file:
    path: "{{ tinypilot_dir }}"
    state: directory
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"

- name: get TinyPilot repo
  git:
    repo: "{{ tinypilot_repo }}"
    dest: "{{ tinypilot_dir }}"
    version: "{{ tinypilot_repo_branch }}"
    accept_hostkey: yes
  notify:
    - restart TinyPilot service

- name: find absolute path to python3
  shell: realpath $(which python3)
  register: realpath_python3
  changed_when: false

- name: save absolute path to python3
  set_fact:
    python3_abs_path: "{{ realpath_python3.stdout }}"

- name: create TinyPilot virtualenv
  pip:
    virtualenv: "{{ tinypilot_dir }}/venv"
    virtualenv_command: "{{ python3_abs_path }} -m venv venv"
    requirements: "{{ tinypilot_dir }}/requirements.txt"
    extra_args: "{{ tinypilot_pip_args }}"
  notify:
    - restart TinyPilot service

- name: fix TinyPilot folder permissions
  file:
    path: "{{ tinypilot_dir }}"
    state: directory
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"
    recurse: yes
  # TODO: Figure out why this fails idempotency otherwise.
  changed_when: false

- name: install TinyPilot as a service
  template:
    src: tinypilot.systemd.j2
    dest: /lib/systemd/system/tinypilot.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload TinyPilot systemd config
    - restart TinyPilot service

- name: enable systemd TinyPilot service file
  systemd:
    name: tinypilot
    enabled: yes
